name: lich_hoc_sv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0  # <--- ĐÃ SỬA: Để thấp xuống cho dễ tương thích

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.7.0 
  numberpicker: ^2.1.2          
  intl: ^0.19.0                 # Định dạng ngày tháng (bản 0.19 ổn định hơn 0.20 một chút)

  
  flutter_local_notifications: ^18.0.1 # Bản 18 hoặc 19 đều ok, nhưng 18 ổn định hơn với timezone
  timezone: ^0.9.2                     # Timezone chuẩn

 
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  path: ^1.9.0
  permission_handler: ^12.0.1
  android_intent_plus: ^6.0.0
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  
  flutter_launcher_icons: ^0.14.2 


flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Nhớ tạo thư mục assets/images ngang hàng với lib


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/penguin.png" 
  min_sdk_android: 21